// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_calls.sql

package db

import (
	"context"
	"time"
)

const countProviderCallsInWindow = `-- name: CountProviderCallsInWindow :one
select count(*)::bigint as calls
from ai_calls
where provider = $1::text
  and created_at > now() - make_interval(secs => $2::int)
`

type CountProviderCallsInWindowParams struct {
	Provider   string
	WindowSecs int32
}

// How much of ONE provider's daily quota this service has spent inside the
// rolling window, across every kind. The global half of the ceiling.
//
// Scoped by provider, not global-global: Google's exhaustion must not refuse an
// Anthropic-backed feature that still has quota (migration 00007).
func (q *Queries) CountProviderCallsInWindow(ctx context.Context, arg CountProviderCallsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderCallsInWindow, arg.Provider, arg.WindowSecs)
	var calls int64
	err := row.Scan(&calls)
	return calls, err
}

const countUserKindCallsInWindow = `-- name: CountUserKindCallsInWindow :one
select count(*)::bigint as calls
from ai_calls
where user_id = $1::uuid
  and kind = $2::text
  and created_at > now() - make_interval(secs => $3::int)
`

type CountUserKindCallsInWindowParams struct {
	UserID     string
	Kind       string
	WindowSecs int32
}

// One player's spend on ONE kind inside the rolling window — the per-kind,
// per-user ceiling (docs/GAME.md §4.3).
//
// Rows with a null user_id are the provider-side halves and are excluded by the
// equality itself (null = $1 is null, never true), which is also why the
// supporting index is partial.
func (q *Queries) CountUserKindCallsInWindow(ctx context.Context, arg CountUserKindCallsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserKindCallsInWindow, arg.UserID, arg.Kind, arg.WindowSecs)
	var calls int64
	err := row.Scan(&calls)
	return calls, err
}

const deleteAICallsBefore = `-- name: DeleteAICallsBefore :execrows
delete from ai_calls
where created_at < $1
`

// Retention sweep. Nothing is ever READ past the 24h window, but rows are kept a
// week so "why did the ceiling refuse me last Tuesday" has an answer; a week at
// the hard ceiling is a few thousand rows, which is not a storage problem.
func (q *Queries) DeleteAICallsBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAICallsBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordAICall = `-- name: RecordAICall :exec

insert into ai_calls (user_id, kind, provider)
values ($1, $2, $3)
`

type RecordAICallParams struct {
	UserID   *string
	Kind     string
	Provider *string
}

// The AI-call ledger (migration 00007) — the whole daily budget, in four
// statements that do not grow when a new AI feature ships. Compare
// queries/judge_budget.sql, which this replaces: that one needed a new UNION arm
// and a fresh "which column means spent" argument per feature.
// Append one ledger row. Called by aibudget.Spend, never directly: exactly one
// row per call carries the provider and one row per billed player carries the
// user, and the pairing is that function's job (migration 00007).
func (q *Queries) RecordAICall(ctx context.Context, arg RecordAICallParams) error {
	_, err := q.db.Exec(ctx, recordAICall, arg.UserID, arg.Kind, arg.Provider)
	return err
}
