// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_calls.sql

package db

import (
	"context"
	"time"
)

const countProviderCallsInWindow = `-- name: CountProviderCallsInWindow :one
select count(*)::bigint as calls
from ai_calls
where provider = $1::text
  and created_at > now() - make_interval(secs => $2::int)
`

type CountProviderCallsInWindowParams struct {
	Provider   string
	WindowSecs int32
}

// How much of ONE provider's daily quota this service has spent inside the
// rolling window, across every kind. The global half of the ceiling.
//
// Scoped by provider, not global-global: Google's exhaustion must not refuse an
// Anthropic-backed feature that still has quota (migration 00007).
func (q *Queries) CountProviderCallsInWindow(ctx context.Context, arg CountProviderCallsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderCallsInWindow, arg.Provider, arg.WindowSecs)
	var calls int64
	err := row.Scan(&calls)
	return calls, err
}

const countUserKindCallsInWindow = `-- name: CountUserKindCallsInWindow :one

select count(*)::bigint as calls
from ai_calls
where user_id = $1::uuid
  and kind = $2::text
  and created_at > now() - make_interval(secs => $3::int)
`

type CountUserKindCallsInWindowParams struct {
	UserID     string
	Kind       string
	WindowSecs int32
}

// The AI-call ledger (migration 00007) — the whole daily budget, in six
// statements that do not grow when a new AI feature ships. Compare
// queries/judge_budget.sql, which this replaces: that one needed a new UNION arm
// and a fresh "which column means spent" argument per feature.
//
// A row's two shapes are two different FACTS that happen at two different
// moments, which is why there are three write statements and not one:
//
//   - a player row says "this player was granted a round of this kind" — written
//     when the round starts;
//   - a provider row says "one request to the provider is about to be made" —
//     written where that is true, which for a duel is the flip to `judging` and
//     not the flip to `drawing`.
//
// Only the single-actor features (practice, guess, assist) do both in the same
// instant, and they get one statement that does both or neither.
// One player's spend on ONE kind inside the rolling window — the per-kind,
// per-user ceiling (docs/GAME.md §4.3).
//
// Rows with a null user_id are the provider-side halves and are excluded by the
// equality itself (null = $1 is null, never true), which is also why the
// supporting index is partial.
func (q *Queries) CountUserKindCallsInWindow(ctx context.Context, arg CountUserKindCallsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserKindCallsInWindow, arg.UserID, arg.Kind, arg.WindowSecs)
	var calls int64
	err := row.Scan(&calls)
	return calls, err
}

const deleteAICallsBefore = `-- name: DeleteAICallsBefore :execrows
delete from ai_calls
where created_at < $1
`

// Retention sweep. Nothing is ever READ past the 24h window, but rows are kept a
// week so "why did the ceiling refuse me last Tuesday" has an answer; a week at
// the hard ceiling is a few thousand rows, which is not a storage problem.
//
// It is a sequential scan: both indexes on this table are partial and lead on
// user_id/provider, so neither can serve a bare created_at predicate. At a few
// thousand rows that is cheaper than the third index it would take to avoid, and
// it runs hourly on a background goroutine where nobody is waiting for it.
func (q *Queries) DeleteAICallsBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAICallsBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordAICallUnderCap = `-- name: RecordAICallUnderCap :execrows
insert into ai_calls (user_id, kind, provider)
select r.user_id, $1::text, r.provider
from (
    -- the player-side row: whose allowance this call spends
    select $2::uuid as user_id, null::text as provider
    union all
    -- the provider-side row: the one request this call makes
    select null::uuid, $3::text
) as r
where (
    select count(*)
    from ai_calls
    where user_id = $2::uuid
      and kind = $1::text
      and created_at > now() - make_interval(secs => $4::int)
) < $5::int
`

type RecordAICallUnderCapParams struct {
	Kind       string
	UserID     string
	Provider   string
	WindowSecs int32
	Cap        int32
}

// The single-actor spend: one player row and one provider row, written together
// or not at all, and only while that player is under their per-kind cap.
//
// It is ONE statement for two reasons. The cheap one is the round trip. The
// load-bearing one is atomicity without a transaction: the two rows are the two
// halves of one call, and a failure between two separate inserts would leave a
// provider row billing a request that the refusal means nobody will make.
//
// The WHERE does not reference the UNION's rows, so it holds for both or for
// neither: this inserts exactly 2 rows or exactly 0. Zero is the refusal, and
// the caller turns it into the same *KindSpentError the advisory check returns.
//
// What the condition buys, honestly: under READ COMMITTED two concurrent
// statements can each still see the same pre-insert count and each insert, so
// the cap is not exact. What shrinks is the window in which that can happen —
// from "an advisory read, then a render, then a provider call" down to "one
// statement" — which is the difference between a measured 12x overshoot under a
// 25-request burst and an overshoot bounded by how many inserts genuinely
// overlap inside Postgres. Exactness would need SERIALIZABLE or a per-user lock;
// neither is worth serializing every AI call for a ceiling that already sits
// below the provider's own.
func (q *Queries) RecordAICallUnderCap(ctx context.Context, arg RecordAICallUnderCapParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordAICallUnderCap,
		arg.Kind,
		arg.UserID,
		arg.Provider,
		arg.WindowSecs,
		arg.Cap,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordPlayerAICalls = `-- name: RecordPlayerAICalls :exec
insert into ai_calls (user_id, kind)
select unnest($1::uuid[]), $2::text
`

type RecordPlayerAICallsParams struct {
	UserIds []string
	Kind    string
}

// The player half on its own: N player rows, no provider row, in one statement.
//
// This is the duel's shape, and the only caller that needs it. Two players are
// granted one round by a single act (the second seat filling), so their rows are
// written together, inside the same transaction that starts the round — one
// statement rather than one per player so a partial write is not a state the
// ledger can reach.
//
// Unconditional, unlike RecordAICallUnderCap, because there is nobody here to
// refuse: the joiner was already checked before the transaction opened, and the
// OTHER seat is being granted a round by somebody else's action. Dropping their
// row would make the ledger undercount a round that really happened, and failing
// the statement would strand a match on a cap that is not the caller's.
func (q *Queries) RecordPlayerAICalls(ctx context.Context, arg RecordPlayerAICallsParams) error {
	_, err := q.db.Exec(ctx, recordPlayerAICalls, arg.UserIds, arg.Kind)
	return err
}

const recordProviderAICall = `-- name: RecordProviderAICall :exec
insert into ai_calls (kind, provider)
values ($1::text, $2::text)
`

type RecordProviderAICallParams struct {
	Kind     string
	Provider string
}

// The provider half on its own: one row, one request about to be made.
//
// Unconditional on purpose, and NOT gated on the global ceiling. By the time a
// duel reaches judging the round has been played: two people drew for ninety
// seconds, and refusing here would strand the match with nothing to show for it.
// The global ceiling therefore stays advisory and is enforced at the check, back
// when refusing still cost the players nothing.
func (q *Queries) RecordProviderAICall(ctx context.Context, arg RecordProviderAICallParams) error {
	_, err := q.db.Exec(ctx, recordProviderAICall, arg.Kind, arg.Provider)
	return err
}
