// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_calls.sql

package db

import (
	"context"
	"time"
)

const countProviderCallsInWindow = `-- name: CountProviderCallsInWindow :one
select count(*)::bigint as calls
from ai_calls
where provider = $1::text
  and created_at > now() - make_interval(secs => $2::int)
`

type CountProviderCallsInWindowParams struct {
	Provider   string
	WindowSecs int32
}

// One provider's spend inside the rolling window, across every kind — the
// global half of the ceiling (docs/GAME.md §4.3), scoped per provider so one
// exhausted provider can't refuse a feature served by another.
func (q *Queries) CountProviderCallsInWindow(ctx context.Context, arg CountProviderCallsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderCallsInWindow, arg.Provider, arg.WindowSecs)
	var calls int64
	err := row.Scan(&calls)
	return calls, err
}

const countUserKindCallsInWindow = `-- name: CountUserKindCallsInWindow :one

select count(*)::bigint as calls
from ai_calls
where user_id = $1::uuid
  and kind = $2::text
  and created_at > now() - make_interval(secs => $3::int)
`

type CountUserKindCallsInWindowParams struct {
	UserID     string
	Kind       string
	WindowSecs int32
}

// The AI-call ledger (docs/GAME.md §4.3): one table for every AI feature's daily
// budget. A row bills either a player (their per-kind allowance) or a provider
// (its quota), never both, since for a duel the two happen at different moments.
// One player's spend on one kind inside the rolling window — the per-kind cap
// (docs/GAME.md §4.3). Rows with a null user_id are provider rows, excluded by
// the equality itself (null = $1 is never true) — why the index is partial.
func (q *Queries) CountUserKindCallsInWindow(ctx context.Context, arg CountUserKindCallsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserKindCallsInWindow, arg.UserID, arg.Kind, arg.WindowSecs)
	var calls int64
	err := row.Scan(&calls)
	return calls, err
}

const deleteAICallsBefore = `-- name: DeleteAICallsBefore :execrows
delete from ai_calls
where created_at < $1
`

// Retention sweep to a week (docs/GAME.md §4.3). Runs as a sequential scan: both
// indexes on this table are partial and lead on user_id/provider, so neither can
// serve a bare created_at predicate.
func (q *Queries) DeleteAICallsBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAICallsBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordAICallUnderCap = `-- name: RecordAICallUnderCap :execrows
insert into ai_calls (user_id, kind, provider)
select r.user_id, $1::text, r.provider
from (
    -- the player-side row: whose allowance this call spends
    select $2::uuid as user_id, null::text as provider
    union all
    -- the provider-side row: the one request this call makes
    select null::uuid, $3::text
) as r
where (
    select count(*)
    from ai_calls
    where user_id = $2::uuid
      and kind = $1::text
      and created_at > now() - make_interval(secs => $4::int)
) < $5::int
`

type RecordAICallUnderCapParams struct {
	Kind       string
	UserID     string
	Provider   string
	WindowSecs int32
	Cap        int32
}

// Writes the player and provider rows together, only while under the per-kind
// cap — one statement, so a crash between two inserts can't bill a provider for
// a request nobody makes. Inserts 2 rows or 0; the caller turns 0 into the same
// *KindSpentError the advisory check returns. Not exact under concurrent
// writers (docs/GAME.md §4.3, "How exact the two halves are").
func (q *Queries) RecordAICallUnderCap(ctx context.Context, arg RecordAICallUnderCapParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordAICallUnderCap,
		arg.Kind,
		arg.UserID,
		arg.Provider,
		arg.WindowSecs,
		arg.Cap,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordPlayerAICalls = `-- name: RecordPlayerAICalls :exec
insert into ai_calls (user_id, kind)
select unnest($1::uuid[]), $2::text
`

type RecordPlayerAICallsParams struct {
	UserIds []string
	Kind    string
}

// The duel's player half: N player rows, no provider row, in one statement so
// the roster is billed together when the second seat fills the round (docs/GAME.md
// §4.3). Unconditional, unlike RecordAICallUnderCap: the joiner was already
// checked before the transaction opened, and the other seat's round is granted
// by that same action, not by them, so dropping their row would undercount a
// round that really happened.
func (q *Queries) RecordPlayerAICalls(ctx context.Context, arg RecordPlayerAICallsParams) error {
	_, err := q.db.Exec(ctx, recordPlayerAICalls, arg.UserIds, arg.Kind)
	return err
}

const recordProviderAICall = `-- name: RecordProviderAICall :exec
insert into ai_calls (kind, provider)
values ($1::text, $2::text)
`

type RecordProviderAICallParams struct {
	Kind     string
	Provider string
}

// The duel's provider half: one row per judging pass. Unconditional and not
// gated on the global ceiling — by the time judging is reached the round has
// been played, and refusing here would strand the match for nothing (docs/GAME.md
// §4.3).
func (q *Queries) RecordProviderAICall(ctx context.Context, arg RecordProviderAICallParams) error {
	_, err := q.db.Exec(ctx, recordProviderAICall, arg.Kind, arg.Provider)
	return err
}
