// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drawings.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const createDrawing = `-- name: CreateDrawing :one
insert into drawings (owner_id, match_id, name, doc_version, width, height, document, thumbnail_url)
values ($1,
        $2,
        coalesce($3::text, 'new art'),
        $4,
        $5,
        $6,
        $7,
        $8)
returning id, owner_id, match_id, doc_version, width, height, document, thumbnail_url, created_at, updated_at, name
`

type CreateDrawingParams struct {
	OwnerID      string
	MatchID      *string
	Name         *string
	DocVersion   int32
	Width        int32
	Height       int32
	Document     json.RawMessage
	ThumbnailUrl *string
}

// `name` is user-editable metadata, NOT part of the vector document (the
// validators never see it — docs/API.md §7). A null name takes the default
// 'new art' (same value as the column default) via coalesce, so callers with
// no name concept — game submit — simply pass nil.
func (q *Queries) CreateDrawing(ctx context.Context, arg CreateDrawingParams) (Drawing, error) {
	row := q.db.QueryRow(ctx, createDrawing,
		arg.OwnerID,
		arg.MatchID,
		arg.Name,
		arg.DocVersion,
		arg.Width,
		arg.Height,
		arg.Document,
		arg.ThumbnailUrl,
	)
	var i Drawing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.MatchID,
		&i.DocVersion,
		&i.Width,
		&i.Height,
		&i.Document,
		&i.ThumbnailUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const deleteDrawing = `-- name: DeleteDrawing :execrows
delete from drawings
where id = $1 and owner_id = $2 and match_id is null
`

type DeleteDrawingParams struct {
	ID      string
	OwnerID string
}

// Same immutability guard as UpdateDrawing: a submitted duel drawing cannot be
// deleted via CRUD (it is referenced by match_players.drawing_id — docs/API.md §7).
func (q *Queries) DeleteDrawing(ctx context.Context, arg DeleteDrawingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDrawing, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDrawing = `-- name: GetDrawing :one
select id, owner_id, match_id, doc_version, width, height, document, thumbnail_url, created_at, updated_at, name from drawings
where id = $1 and owner_id = $2
`

type GetDrawingParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) GetDrawing(ctx context.Context, arg GetDrawingParams) (Drawing, error) {
	row := q.db.QueryRow(ctx, getDrawing, arg.ID, arg.OwnerID)
	var i Drawing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.MatchID,
		&i.DocVersion,
		&i.Width,
		&i.Height,
		&i.Document,
		&i.ThumbnailUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const listDrawings = `-- name: ListDrawings :many
select id, owner_id, match_id, name, doc_version, width, height, thumbnail_url, created_at, updated_at
from drawings
where owner_id = $1
  and (
    $2::text = 'all'
    or ($2::text = 'free' and match_id is null)
    or ($2::text = 'duel' and match_id is not null)
  )
  and (
    $3::timestamptz is null
    or (created_at, id) < ($3::timestamptz, $4::uuid)
  )
order by created_at desc, id desc
limit $5
`

type ListDrawingsParams struct {
	OwnerID         string
	Kind            string
	CursorCreatedAt *time.Time
	CursorID        *string
	PageLimit       int32
}

type ListDrawingsRow struct {
	ID           string
	OwnerID      string
	MatchID      *string
	Name         string
	DocVersion   int32
	Width        int32
	Height       int32
	ThumbnailUrl *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// Metadata only (no document body) — keeps the list cheap (docs/API.md §7).
// Keyset pagination on (created_at desc, id desc); kind filters free/duel/all.
func (q *Queries) ListDrawings(ctx context.Context, arg ListDrawingsParams) ([]ListDrawingsRow, error) {
	rows, err := q.db.Query(ctx, listDrawings,
		arg.OwnerID,
		arg.Kind,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDrawingsRow
	for rows.Next() {
		var i ListDrawingsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.MatchID,
			&i.Name,
			&i.DocVersion,
			&i.Width,
			&i.Height,
			&i.ThumbnailUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDrawing = `-- name: UpdateDrawing :one
update drawings
set name        = coalesce($1::text, name),
    doc_version = $2,
    width       = $3,
    height      = $4,
    document    = $5,
    updated_at  = now()
where id = $6 and owner_id = $7 and match_id is null
returning id, owner_id, match_id, doc_version, width, height, document, thumbnail_url, created_at, updated_at, name
`

type UpdateDrawingParams struct {
	Name       *string
	DocVersion int32
	Width      int32
	Height     int32
	Document   json.RawMessage
	ID         string
	OwnerID    string
}

// `match_id is null` makes a submitted duel drawing immutable via CRUD (it is
// locked once submitted — docs/API.md §7). A match-linked row matches nothing
// here; the service turns that miss into 409, not a silent 404.
// thumbnail_url is intentionally NOT set here: it is a server-generated cached-PNG
// URL (the render worker owns it — DOCUMENT-FORMAT §7), never a client field, so a
// document CRUD update must leave it untouched rather than clobber it to NULL.
// `name` uses coalesce so a null (name absent/blank in the request) KEEPS the
// existing name instead of clobbering it — an update is a document replace, not
// necessarily a rename (docs/API.md §7).
func (q *Queries) UpdateDrawing(ctx context.Context, arg UpdateDrawingParams) (Drawing, error) {
	row := q.db.QueryRow(ctx, updateDrawing,
		arg.Name,
		arg.DocVersion,
		arg.Width,
		arg.Height,
		arg.Document,
		arg.ID,
		arg.OwnerID,
	)
	var i Drawing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.MatchID,
		&i.DocVersion,
		&i.Width,
		&i.Height,
		&i.Document,
		&i.ThumbnailUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
