// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match_players.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const countUnsubmitted = `-- name: CountUnsubmitted :one
select count(*) from match_players
where match_id = $1 and submitted_at is null
`

// How many roster slots have not submitted yet. Read under the match row lock
// (GetMatchForUpdate) so the last-submit → judging flip can't race.
func (q *Queries) CountUnsubmitted(ctx context.Context, matchID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnsubmitted, matchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMatchPlayer = `-- name: GetMatchPlayer :one
select match_id, user_id, drawing_id, score, rating_before, rating_after, submitted_at from match_players
where match_id = $1 and user_id = $2
`

type GetMatchPlayerParams struct {
	MatchID string
	UserID  string
}

// One roster slot — used at submit to decide 403 (not a player) vs 409 (already
// submitted). submitted_at != null ⇒ this player has already submitted.
func (q *Queries) GetMatchPlayer(ctx context.Context, arg GetMatchPlayerParams) (MatchPlayer, error) {
	row := q.db.QueryRow(ctx, getMatchPlayer, arg.MatchID, arg.UserID)
	var i MatchPlayer
	err := row.Scan(
		&i.MatchID,
		&i.UserID,
		&i.DrawingID,
		&i.Score,
		&i.RatingBefore,
		&i.RatingAfter,
		&i.SubmittedAt,
	)
	return i, err
}

const getMatchPlayerDrawing = `-- name: GetMatchPlayerDrawing :one
select d.document
from drawings d
         join match_players tp
              on tp.drawing_id = d.id
                  and tp.match_id = $1
                  and tp.user_id = $2
                  -- Defence-in-depth backstops (belt-and-suspenders, not load-bearing today):
                  -- the drawing must be the target's OWN and linked to THIS match. The write
                  -- path already guarantees this (StampSubmission only ever points drawing_id at
                  -- a fresh CreateDrawing with owner_id = that player, match_id = this match), so
                  -- these predicates change nothing now — but they make the correctness hold
                  -- BY CONSTRUCTION, not by invariant, if a future write path ever diverges, and
                  -- they fail closed if the positional $2/$3 (target/viewer) binds ever swap.
                  and d.owner_id = $2
                  and d.match_id = $1
         join matches m
              on m.id = $1
                  and m.status = 'done'
where exists (select 1
              from match_players vp
              where vp.match_id = $1
                and vp.user_id = $3)
`

type GetMatchPlayerDrawingParams struct {
	MatchID      string
	TargetUserID string
	ViewerUserID string
}

// The vector document a match participant (`target_user_id`) submitted, revealed
// to a FELLOW participant (`viewer_user_id`) ONLY once the match is `done`. One
// row folds three trust gates; any miss yields no row, which the service maps to a
// hidden 404 that never says which gate failed:
//   - viewer_user_id must be a player of this match      (IDOR)
//   - the match must be `done`                           (no peeking at the opponent mid-duel, GAME.md §4.2)
//   - target_user_id must be a submitted player of it    (enumeration; the INNER JOIN needs a non-null drawing_id)
//
// The ownership-scoped GetDrawing can't serve this (it 404s a non-owner), so
// match membership is the authorization here (docs/IDEAS.md) — no object storage
// needed, the caller renders the returned document client-side.
func (q *Queries) GetMatchPlayerDrawing(ctx context.Context, arg GetMatchPlayerDrawingParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getMatchPlayerDrawing, arg.MatchID, arg.TargetUserID, arg.ViewerUserID)
	var document json.RawMessage
	err := row.Scan(&document)
	return document, err
}

const getMatchPlayersForResolve = `-- name: GetMatchPlayersForResolve :many
select mp.user_id,
       mp.submitted_at,
       mp.drawing_id,
       u.rating
from match_players mp
join users u on u.id = mp.user_id
where mp.match_id = $1
order by mp.submitted_at asc nulls last, mp.user_id asc
`

type GetMatchPlayersForResolveRow struct {
	UserID      string
	SubmittedAt *time.Time
	DrawingID   *string
	Rating      int32
}

// Per-player state the deadline resolver needs in one read: who submitted (and
// their drawing), plus the live rating for forfeit Elo. Stable (submitted_at,
// user_id) order — the same A/B seat ordering judging uses (docs/GAME.md §7.1).
func (q *Queries) GetMatchPlayersForResolve(ctx context.Context, matchID string) ([]GetMatchPlayersForResolveRow, error) {
	rows, err := q.db.Query(ctx, getMatchPlayersForResolve, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMatchPlayersForResolveRow
	for rows.Next() {
		var i GetMatchPlayersForResolveRow
		if err := rows.Scan(
			&i.UserID,
			&i.SubmittedAt,
			&i.DrawingID,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubmissionsForJudging = `-- name: GetSubmissionsForJudging :many
select mp.user_id,
       mp.drawing_id,
       mp.submitted_at,
       u.rating,
       d.document
from match_players mp
join users u on u.id = mp.user_id
join drawings d on d.id = mp.drawing_id
where mp.match_id = $1
order by mp.submitted_at asc, mp.user_id asc
`

type GetSubmissionsForJudgingRow struct {
	UserID      string
	DrawingID   *string
	SubmittedAt *time.Time
	Rating      int32
	Document    json.RawMessage
}

// The two submissions with each player's live rating and their drawing document,
// ordered by (submitted_at, user_id) — the stable A/B ordering (docs/GAME.md §7.1):
// row 0 = image A, row 1 = image B. No `nulls last` (unlike ListMatchPlayers): the
// INNER JOIN on drawings admits only stamped rows, so submitted_at is never null
// here. Don't switch this to a LEFT JOIN or the A/B bind becomes nondeterministic.
func (q *Queries) GetSubmissionsForJudging(ctx context.Context, matchID string) ([]GetSubmissionsForJudgingRow, error) {
	rows, err := q.db.Query(ctx, getSubmissionsForJudging, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubmissionsForJudgingRow
	for rows.Next() {
		var i GetSubmissionsForJudgingRow
		if err := rows.Scan(
			&i.UserID,
			&i.DrawingID,
			&i.SubmittedAt,
			&i.Rating,
			&i.Document,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlayerScore = `-- name: SetPlayerScore :exec
update match_players
set score = $3, rating_before = $4, rating_after = $5
where match_id = $1 and user_id = $2
`

type SetPlayerScoreParams struct {
	MatchID      string
	UserID       string
	Score        *float64
	RatingBefore *int32
	RatingAfter  *int32
}

// Record the judge's per-player score and the Elo snapshot around the match
// (docs/GAME.md §8).
func (q *Queries) SetPlayerScore(ctx context.Context, arg SetPlayerScoreParams) error {
	_, err := q.db.Exec(ctx, setPlayerScore,
		arg.MatchID,
		arg.UserID,
		arg.Score,
		arg.RatingBefore,
		arg.RatingAfter,
	)
	return err
}

const stampSubmission = `-- name: StampSubmission :execrows
update match_players
set drawing_id = $3, submitted_at = now()
where match_id = $1 and user_id = $2 and submitted_at is null
`

type StampSubmissionParams struct {
	MatchID   string
	UserID    string
	DrawingID *string
}

// Record a player's submission. The `submitted_at is null` guard makes it
// idempotent: a double-submit stamps zero rows (the handler answers 409).
func (q *Queries) StampSubmission(ctx context.Context, arg StampSubmissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, stampSubmission, arg.MatchID, arg.UserID, arg.DrawingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserRating = `-- name: UpdateUserRating :exec
update users
set rating = $2, updated_at = now()
where id = $1
`

type UpdateUserRatingParams struct {
	ID     string
	Rating int32
}

func (q *Queries) UpdateUserRating(ctx context.Context, arg UpdateUserRatingParams) error {
	_, err := q.db.Exec(ctx, updateUserRating, arg.ID, arg.Rating)
	return err
}
