// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package db

import (
	"context"
	"time"
)

const addMatchPlayer = `-- name: AddMatchPlayer :exec
insert into match_players (match_id, user_id)
values ($1, $2)
`

type AddMatchPlayerParams struct {
	MatchID string
	UserID  string
}

// Insert one roster slot. The composite PK (match_id, user_id) makes a double
// join impossible.
func (q *Queries) AddMatchPlayer(ctx context.Context, arg AddMatchPlayerParams) error {
	_, err := q.db.Exec(ctx, addMatchPlayer, arg.MatchID, arg.UserID)
	return err
}

const createMatch = `-- name: CreateMatch :one
insert into matches (prompt_id)
values ($1)
returning id, prompt_id, mode, status, winner_player_id, judge_reason, created_at, updated_at
`

// A fresh open async match with one prompt pinned; mode/status use their column
// defaults ('async'/'open'). docs/GAME.md §4.1.
func (q *Queries) CreateMatch(ctx context.Context, promptID string) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch, promptID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.Mode,
		&i.Status,
		&i.WinnerPlayerID,
		&i.JudgeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findMyOpenMatch = `-- name: FindMyOpenMatch :one
select m.id, m.prompt_id, m.mode, m.status, m.winner_player_id, m.judge_reason, m.created_at, m.updated_at from matches m
join match_players mp on mp.match_id = m.id
where m.status = 'open'
  and m.mode = 'async'
  and mp.user_id = $1
order by m.created_at asc
limit 1
`

// The caller's own still-open match, if any — returned instead of stacking a
// second open match when a waiting player taps "play" again.
func (q *Queries) FindMyOpenMatch(ctx context.Context, userID string) (Match, error) {
	row := q.db.QueryRow(ctx, findMyOpenMatch, userID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.Mode,
		&i.Status,
		&i.WinnerPlayerID,
		&i.JudgeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOpenMatchToJoin = `-- name: FindOpenMatchToJoin :one
select id, prompt_id, mode, status, winner_player_id, judge_reason, created_at, updated_at from matches
where status = 'open'
  and mode = 'async'
  and not exists (
    select 1 from match_players mp
    where mp.match_id = matches.id and mp.user_id = $1
  )
order by created_at asc
limit 1
for update skip locked
`

// The oldest open async match the caller is NOT already in — the auto-join
// candidate (docs/GAME.md §4.1, docs/DECISIONS.md "Matchmaking"). FOR UPDATE
// SKIP LOCKED lets concurrent joiners each grab a different match instead of
// colliding on one (the loser skips the locked row and creates its own).
func (q *Queries) FindOpenMatchToJoin(ctx context.Context, userID string) (Match, error) {
	row := q.db.QueryRow(ctx, findOpenMatchToJoin, userID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.Mode,
		&i.Status,
		&i.WinnerPlayerID,
		&i.JudgeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMatch = `-- name: GetMatch :one
select id, prompt_id, mode, status, winner_player_id, judge_reason, created_at, updated_at from matches
where id = $1
`

func (q *Queries) GetMatch(ctx context.Context, id string) (Match, error) {
	row := q.db.QueryRow(ctx, getMatch, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.Mode,
		&i.Status,
		&i.WinnerPlayerID,
		&i.JudgeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMatchForUpdate = `-- name: GetMatchForUpdate :one
select id, prompt_id, mode, status, winner_player_id, judge_reason, created_at, updated_at from matches
where id = $1
for update
`

// Same as GetMatch but takes a row lock, serializing concurrent submits to one
// match so the last-submit → judging flip is computed on a stable roster (two
// players submitting at the same instant can't both miss "I'm last").
func (q *Queries) GetMatchForUpdate(ctx context.Context, id string) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchForUpdate, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.Mode,
		&i.Status,
		&i.WinnerPlayerID,
		&i.JudgeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMatchPlayers = `-- name: ListMatchPlayers :many
select mp.match_id,
       mp.user_id,
       mp.drawing_id,
       mp.score,
       mp.rating_before,
       mp.rating_after,
       mp.submitted_at,
       u.display_name
from match_players mp
join users u on u.id = mp.user_id
where mp.match_id = $1
order by mp.submitted_at asc nulls last, mp.user_id asc
`

type ListMatchPlayersRow struct {
	MatchID      string
	UserID       string
	DrawingID    *string
	Score        *float64
	RatingBefore *int32
	RatingAfter  *int32
	SubmittedAt  *time.Time
	DisplayName  *string
}

// The roster for a match, with each player's optional display name. `login` is
// deliberately NOT selected — it may be an email, and the opponent must not see
// it (privacy). Ordered by submit time then user_id: the same stable ordering
// the A/B→player mapping will use at judging (docs/GAME.md §7.1).
func (q *Queries) ListMatchPlayers(ctx context.Context, matchID string) ([]ListMatchPlayersRow, error) {
	rows, err := q.db.Query(ctx, listMatchPlayers, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchPlayersRow
	for rows.Next() {
		var i ListMatchPlayersRow
		if err := rows.Scan(
			&i.MatchID,
			&i.UserID,
			&i.DrawingID,
			&i.Score,
			&i.RatingBefore,
			&i.RatingAfter,
			&i.SubmittedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMatchResult = `-- name: SetMatchResult :one
update matches
set status = 'done', winner_player_id = $2, judge_reason = $3, updated_at = now()
where id = $1
returning id, prompt_id, mode, status, winner_player_id, judge_reason, created_at, updated_at
`

type SetMatchResultParams struct {
	ID             string
	WinnerPlayerID *string
	JudgeReason    *string
}

// Terminal write for the judging → done transition: winner (null = tie), the
// judge's reason verbatim, status done (docs/GAME.md §4.1, §7.1).
func (q *Queries) SetMatchResult(ctx context.Context, arg SetMatchResultParams) (Match, error) {
	row := q.db.QueryRow(ctx, setMatchResult, arg.ID, arg.WinnerPlayerID, arg.JudgeReason)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.Mode,
		&i.Status,
		&i.WinnerPlayerID,
		&i.JudgeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMatchStatus = `-- name: UpdateMatchStatus :one
update matches
set status = $2, updated_at = now()
where id = $1
returning id, prompt_id, mode, status, winner_player_id, judge_reason, created_at, updated_at
`

type UpdateMatchStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatchStatus, arg.ID, arg.Status)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.Mode,
		&i.Status,
		&i.WinnerPlayerID,
		&i.JudgeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
