// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"
)

type Drawing struct {
	ID           string
	OwnerID      string
	MatchID      *string
	DocVersion   int32
	Width        int32
	Height       int32
	Document     json.RawMessage
	ThumbnailUrl *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Name         string
}

type Match struct {
	ID               string
	PromptID         string
	Mode             string
	Status           string
	WinnerPlayerID   *string
	JudgeReason      *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DrawingDeadline  *time.Time
	Resolution       *string
	JudgeAttempts    int32
	JudgingStartedAt *time.Time
}

type MatchPlayer struct {
	MatchID      string
	UserID       string
	DrawingID    *string
	Score        *float64
	RatingBefore *int32
	RatingAfter  *int32
	SubmittedAt  *time.Time
}

type Prompt struct {
	ID        string
	Text      string
	Active    bool
	CreatedAt time.Time
}

type User struct {
	ID           string
	Login        string
	PasswordHash string
	DisplayName  *string
	Rating       int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
