// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: practice_runs.sql

package db

import (
	"context"
)

const createPracticeRun = `-- name: CreatePracticeRun :one
insert into practice_runs (user_id, prompt_id)
values ($1, $2)
returning id, user_id, prompt_id, score, feedback, created_at
`

type CreatePracticeRunParams struct {
	UserID   string
	PromptID string
}

// Records the attempt before the critic is called. Score and feedback stay null
// until a verdict comes back; a row that keeps them is a judge call that was
// spent and produced nothing, which still counts against the daily budget
// (docs/GAME.md §4.3). Writing it afterwards instead would make every failure
// free, and a failing critic is exactly when the quota drains.
func (q *Queries) CreatePracticeRun(ctx context.Context, arg CreatePracticeRunParams) (PracticeRun, error) {
	row := q.db.QueryRow(ctx, createPracticeRun, arg.UserID, arg.PromptID)
	var i PracticeRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PromptID,
		&i.Score,
		&i.Feedback,
		&i.CreatedAt,
	)
	return i, err
}

const setPracticeRunVerdict = `-- name: SetPracticeRunVerdict :one
update practice_runs
set score = $1::double precision,
    feedback = $2::text
where id = $3
  and user_id = $4
returning id, user_id, prompt_id, score, feedback, created_at
`

type SetPracticeRunVerdictParams struct {
	Score    float64
	Feedback string
	ID       string
	UserID   string
}

// Stamps the critique onto an attempt this user owns. Scoped by user_id as well
// as id, like every write here, so `returning` with no row back tells the caller
// the row wasn't reachable rather than that the update silently landed. The
// casts pin both parameters non-null on the Go side: the columns are nullable
// because an attempt starts without a verdict, but this statement only ever
// runs with one.
func (q *Queries) SetPracticeRunVerdict(ctx context.Context, arg SetPracticeRunVerdictParams) (PracticeRun, error) {
	row := q.db.QueryRow(ctx, setPracticeRunVerdict,
		arg.Score,
		arg.Feedback,
		arg.ID,
		arg.UserID,
	)
	var i PracticeRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PromptID,
		&i.Score,
		&i.Feedback,
		&i.CreatedAt,
	)
	return i, err
}
