// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prompts.sql

package db

import (
	"context"
)

const getActivePromptByID = `-- name: GetActivePromptByID :one
select id, text, active, created_at from prompts
where id = $1 and active
`

// The prompt a practice run claims to be answering. `active` is part of the
// lookup, not a field the caller checks afterwards: a deactivated prompt must read
// as "no such prompt" (→ 404), the same answer a made-up id gets, so retiring a
// prompt cannot be detected by trying to draw for it. A duel pins its prompt
// server-side and so has no equivalent — only practice takes an id from a client.
func (q *Queries) GetActivePromptByID(ctx context.Context, id string) (Prompt, error) {
	row := q.db.QueryRow(ctx, getActivePromptByID, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptByID = `-- name: GetPromptByID :one
select id, text, active, created_at from prompts
where id = $1
`

func (q *Queries) GetPromptByID(ctx context.Context, id string) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPromptByID, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const pickRandomActivePrompt = `-- name: PickRandomActivePrompt :one
select id, text, active, created_at from prompts
where active
order by random()
limit 1
`

// Selection (v1) is random among active prompts (docs/GAME.md §5). `order by
// random()` is fine at seed scale (dozens of rows); revisit for a large pool.
func (q *Queries) PickRandomActivePrompt(ctx context.Context) (Prompt, error) {
	row := q.db.QueryRow(ctx, pickRandomActivePrompt)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
