// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prompts.sql

package db

import (
	"context"
)

const getPromptByID = `-- name: GetPromptByID :one
select id, text, active, created_at from prompts
where id = $1
`

func (q *Queries) GetPromptByID(ctx context.Context, id string) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPromptByID, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const pickRandomActivePrompt = `-- name: PickRandomActivePrompt :one
select id, text, active, created_at from prompts
where active
order by random()
limit 1
`

// Selection (v1) is random among active prompts (docs/GAME.md §5). `order by
// random()` is fine at seed scale (dozens of rows); revisit for a large pool.
func (q *Queries) PickRandomActivePrompt(ctx context.Context) (Prompt, error) {
	row := q.db.QueryRow(ctx, pickRandomActivePrompt)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
