// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const applyRatingDelta = `-- name: ApplyRatingDelta :one
update users set rating = rating + $1::int, updated_at = now() where id = $2 returning rating
`

type ApplyRatingDeltaParams struct {
	Delta int32
	ID    string
}

// Atomically move a player's ladder rating by the match's Elo delta and return the
// TRUE post-update rating. rating = rating + delta (never an absolute SET) so two
// matches sharing a player resolving concurrently both land — the match-row lock
// serializes per MATCH, not per USER (docs/NOTES.md).
func (q *Queries) ApplyRatingDelta(ctx context.Context, arg ApplyRatingDeltaParams) (int32, error) {
	row := q.db.QueryRow(ctx, applyRatingDelta, arg.Delta, arg.ID)
	var rating int32
	err := row.Scan(&rating)
	return rating, err
}

const createUser = `-- name: CreateUser :one
insert into users (login, password_hash, display_name)
values ($1, $2, $3)
returning id, login, password_hash, display_name, rating, created_at, updated_at
`

type CreateUserParams struct {
	Login        string
	PasswordHash string
	DisplayName  *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Login, arg.PasswordHash, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, login, password_hash, display_name, rating, created_at, updated_at from users
where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
select id, login, password_hash, display_name, rating, created_at, updated_at from users
where login = $1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
